/**
 * IndexedDB texture cache for procedural Phaser canvas textures.
 *
 * On first visit, procedural textures are generated from canvas drawing code
 * (creatures, beasts, effects, items, etc.) which takes 2–5 seconds.
 * This module serializes those textures to blobs and stores them in IndexedDB.
 * On subsequent visits, textures are restored from cache, skipping generation entirely.
 *
 * Bump TEX_VERSION when texture drawing code changes to invalidate the cache.
 */

/** Bump this when texture drawing code changes to invalidate the cache. */
export const TEX_VERSION = 2;

const DB_NAME = "agent-heights-textures";
const STORE_NAME = "textures";
const META_STORE = "meta";

interface CachedTexture {
  key: string;
  blob: Blob;
  width: number;
  height: number;
  frames?: number; // for spritesheets — number of frames
  frameSize?: number; // for spritesheets — size of each frame
}

let dbPromise: Promise<IDBDatabase> | null = null;

function getDB(): Promise<IDBDatabase> {
  if (dbPromise) return dbPromise;
  dbPromise = new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) {
        db.createObjectStore(STORE_NAME, { keyPath: "key" });
      }
      if (!db.objectStoreNames.contains(META_STORE)) {
        db.createObjectStore(META_STORE, { keyPath: "key" });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
  return dbPromise;
}

/** Check if the cache is valid for the current TEX_VERSION. */
export async function isCacheValid(): Promise<boolean> {
  try {
    const db = await getDB();
    return new Promise((resolve) => {
      const tx = db.transaction(META_STORE, "readonly");
      const store = tx.objectStore(META_STORE);
      const req = store.get("version");
      req.onsuccess = () => {
        const result = req.result as { key: string; value: number } | undefined;
        resolve(result?.value === TEX_VERSION);
      };
      req.onerror = () => resolve(false);
    });
  } catch {
    return false;
  }
}

/** Mark the cache as valid for the current TEX_VERSION. */
async function setCacheValid(): Promise<void> {
  try {
    const db = await getDB();
    const tx = db.transaction(META_STORE, "readwrite");
    tx.objectStore(META_STORE).put({ key: "version", value: TEX_VERSION });
    await new Promise<void>((resolve, reject) => {
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
    });
  } catch {
    // ignore
  }
}

/** Collect all texture keys that were generated by the essential texture steps. */
function collectTextureKeys(tex: Phaser.Textures.TextureManager): string[] {
  const keys: string[] = [];
  // Collect all canvas textures that start with known procedural prefixes.
  // This covers creatures, beasts, friendlies, effects, glows, items, interior walls.
  const prefixes = [
    "creature-", "beast-", "friendly-",
    "stone-proj", "spark", "dust", "shockwave", "recruit-beam", "slash-vfx", "crystal-arrow",
    "soft-glow", "fire-glow", "void-glow", "crystal-glow",
    "golf-club", "golf-bag", "golf-ball", "axe",
    "interior-wall-",
  ];
  for (const key of tex.getTextureKeys()) {
    for (const prefix of prefixes) {
      if (key.startsWith(prefix)) {
        keys.push(key);
        break;
      }
    }
  }
  return keys;
}

/** Save all procedural textures to IndexedDB. Called after texture generation completes. */
export async function saveTextures(tex: Phaser.Textures.TextureManager): Promise<void> {
  try {
    const keys = collectTextureKeys(tex);
    if (keys.length === 0) return;

    // Collect all blobs FIRST, outside any IDB transaction.
    // toBlob() is async — if we await inside a transaction, it will close
    // before we can write ("The transaction has finished" error).
    const entries: CachedTexture[] = [];
    for (const key of keys) {
      const texture = tex.get(key);
      if (!texture) continue;
      const source = texture.getSourceImage() as HTMLCanvasElement;
      if (!source || !(source instanceof HTMLCanvasElement)) continue;

      const blob = await new Promise<Blob | null>((resolve) =>
        source.toBlob((b) => resolve(b), "image/png")
      );
      if (!blob) continue;

      // Count frames excluding __BASE to get the actual spritesheet frame count.
      // Phaser's frameTotal includes __BASE, so subtract 1.
      const frameCount = texture.frameTotal - 1;
      const frameSize = source.height; // spritesheets are horizontal strips, height = frame size

      entries.push({
        key,
        blob,
        width: source.width,
        height: source.height,
        frames: frameCount > 1 ? frameCount : undefined,
        frameSize: frameCount > 1 ? frameSize : undefined,
      });
    }

    if (entries.length === 0) return;

    // Now write all entries in a single synchronous transaction.
    const db = await getDB();
    const tx = db.transaction(STORE_NAME, "readwrite");
    const store = tx.objectStore(STORE_NAME);
    for (const entry of entries) {
      store.put(entry);
    }
    await new Promise<void>((resolve, reject) => {
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
    });

    await setCacheValid();
    console.log(`[tex-cache] saved ${entries.length} textures to IndexedDB`);
  } catch (err) {
    console.warn("[tex-cache] save failed:", err);
  }
}

/** Load textures from IndexedDB and register them with Phaser. Returns true if cache was used. */
export async function loadTextures(tex: Phaser.Textures.TextureManager): Promise<boolean> {
  try {
    const valid = await isCacheValid();
    if (!valid) return false;

    const db = await getDB();
    const allKeys = await new Promise<string[]>((resolve, reject) => {
      const tx = db.transaction(STORE_NAME, "readonly");
      const req = tx.objectStore(STORE_NAME).getAllKeys();
      req.onsuccess = () => resolve(req.result as string[]);
      req.onerror = () => reject(req.error);
    });

    if (allKeys.length === 0) return false;

    let loaded = 0;
    for (const key of allKeys) {
      const result = await new Promise<CachedTexture | undefined>((resolve, reject) => {
        const tx = db.transaction(STORE_NAME, "readonly");
        const req = tx.objectStore(STORE_NAME).get(key);
        req.onsuccess = () => resolve(req.result as CachedTexture | undefined);
        req.onerror = () => reject(req.error);
      });
      if (!result) continue;

      // Convert blob to ImageBitmap, then register with Phaser
      const bitmap = await createImageBitmap(result.blob);
      if (result.frames && result.frameSize) {
        // Spritesheet — add as image and register frames with NUMERIC names
        // (matching how registerFrames() in textures.ts does it: tex.add(f, ...))
        // generateFrameNumbers() in animations expects numeric frame names.
        tex.addImage(key, bitmap as unknown as HTMLImageElement);
        const frameSize = result.frameSize;
        const texture = tex.get(key);
        if (texture) {
          for (let f = 0; f < result.frames; f++) {
            texture.add(f, 0, f * frameSize, 0, frameSize, frameSize);
          }
        }
      } else {
        // Single texture
        tex.addImage(key, bitmap as unknown as HTMLImageElement);
      }
      loaded++;
    }

    console.log(`[tex-cache] loaded ${loaded} textures from IndexedDB`);
    return loaded > 0;
  } catch (err) {
    console.warn("[tex-cache] load failed:", err);
    return false;
  }
}

/** Clear the texture cache (e.g., when TEX_VERSION is bumped). */
export async function clearCache(): Promise<void> {
  try {
    const db = await getDB();
    const tx = db.transaction([STORE_NAME, META_STORE], "readwrite");
    tx.objectStore(STORE_NAME).clear();
    tx.objectStore(META_STORE).clear();
    await new Promise<void>((resolve, reject) => {
      tx.oncomplete = () => resolve();
      tx.onerror = () => reject(tx.error);
    });
    console.log("[tex-cache] cache cleared");
  } catch {
    // ignore
  }
}
