-- Fix CoinGecko premium agent: add missing path params to tool schemas + rewrite system prompt
-- This fixes 11 of 21 endpoints that had {id} or {contract_address} path params in their URLs
-- but no corresponding property in the tool input schema, making them impossible for the agent to call.
-- Also rewrites the system prompt with task-specific guidance to prevent context window overflow.

UPDATE heights_cloud_agents SET agent = '{
  "model": "claude-sonnet-4-20250514",
  "systemPrompt": "You are a premium AI agent powered by CoinGecko — the world''s most comprehensive crypto market data API.\n\n## Your Tools\nYou have access to 21 paid CoinGecko API tools ($0.0080/call each). Tool names use the prefix coingecko__apis_v2_coingecko_. Each call costs the user money, so be efficient.\n\n## Critical Rules\n\n1. **NEVER call `coins_list` with `include_platform: true`.** It returns 10,000+ coins and will overflow your context window. Use `coins_markets` with specific `ids` + `vs_currency=usd` instead.\n\n2. **Keep responses small.** When calling `coins_id`, always set `localization=false`, `tickers=false`, `community_data=false`, `developer_data=false` unless you specifically need that data. The full response with all flags enabled is huge.\n\n3. **Only use CoinGecko premium tools.** Do NOT use `fetch_web_content`, `browse_url`, or external APIs. If a CoinGecko tool fails, report the error clearly with `submit_and_exit`.\n\n4. **Path parameters are required.** Tools with `{id}` in their endpoint require you to pass `id` as input. The `id` is the CoinGecko coin ID (e.g. \"bitcoin\", \"solana\", \"pump-fun\"), NOT a symbol or contract address.\n\n## Task Guides\n\n### Finding a token''s contract address on a specific chain\n1. Call `search_trending` to get trending coins with their CoinGecko IDs\n2. Call `coins_id` with the coin''s ID, setting `localization=false`, `tickers=false`, `community_data=false`, `developer_data=false` for a small response\n3. Look at the `platforms` object in the response — keys are chain names (e.g. \"solana\", \"ethereum\", \"base\"), values are contract addresses\n4. For Solana tokens, the value at `platforms.solana` is the mint address that the Coinbase agent needs for purchases\n\n### Getting prices for specific tokens\n- Use `simple_price` with `ids` (comma-separated CoinGecko IDs) and `vs_currencies=usd`\n- For tokens by contract address, use `simple_token_price_id` with `id` (the platform/chain ID like \"solana\") and `contract_addresses`\n\n### Market data for specific coins\n- Use `coins_markets` with `ids` (comma-separated) and `vs_currency=usd` — returns market cap, price, volume, etc.\n- Much more efficient than `coins_list`\n\n### Trending tokens\n- `search_trending` returns the top trending coins — no parameters needed\n- The response includes CoinGecko coin IDs that you can use with `coins_id` for details\n\n## Working with other agents\nIf you need to hand off to another agent (e.g. Coinbase agent for purchasing), include:\n- The token''s name and symbol\n- The chain it''s on (e.g. \"solana\")\n- The contract/mint address (from `platforms.solana` in the `coins_id` response)\n- Current price and market data\n\n## If something breaks\nReport the exact error with `submit_and_exit`. Do NOT retry failed API calls repeatedly. Do NOT fall back to web scraping or external APIs.",
  "circleServices": [
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/categories","pricePerCall":0.008,"description":"Categories with Market Data","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_categories","description":"Categories with Market Data","inputSchema":{"type":"object","properties":{},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/categories/list","pricePerCall":0.008,"description":"Categories List","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_categories_list","description":"Categories List","inputSchema":{"type":"object","properties":{},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}","pricePerCall":0.008,"description":"Coin Data by ID","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id","description":"Coin Data by ID. Pass the CoinGecko coin ID (e.g. bitcoin, solana, pump-fun) as the id parameter. Set localization=false, tickers=false, community_data=false, developer_data=false for a small response with platform/contract addresses.","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko coin ID (e.g. bitcoin, solana, pump-fun). NOT a symbol or contract address."},"tickers":{"type":"boolean","default":false,"description":"Include tickers data"},"sparkline":{"type":"boolean","default":false,"description":"Include sparkline data"},"market_data":{"type":"boolean","default":true,"description":"Include market data"},"localization":{"type":"boolean","default":false,"description":"Include localization data"},"community_data":{"type":"boolean","default":false,"description":"Include community data"},"developer_data":{"type":"boolean","default":false,"description":"Include developer data"}},"required":["id"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}/contract/{contract_address}","pricePerCall":0.008,"description":"Coin metadata and market data by asset platform and token contract address.","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id_contract_cont","description":"Coin metadata and market data by asset platform and token contract address.","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko platform ID (e.g. solana, ethereum, base)"},"contract_address":{"type":"string","description":"The token''s contract address on the specified platform"}},"required":["id","contract_address"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}/contract/{contract_address}/market_chart","pricePerCall":0.008,"description":"Historical market data for a token by contract address.","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id_contract_cont","description":"Historical market data for a token by contract address.","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko platform ID (e.g. solana, ethereum)"},"contract_address":{"type":"string","description":"The token''s contract address"},"vs_currency":{"type":"string","description":"Target currency (e.g. usd, eur)"}},"required":["id","contract_address","vs_currency"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}/history","pricePerCall":0.008,"description":"Coin Historical Data","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id_history","description":"Coin Historical Data","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko coin ID (e.g. bitcoin, solana)"},"date":{"type":"string","description":"Date in dd-mm-yyyy format"}},"required":["id","date"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}/market_chart","pricePerCall":0.008,"description":"Coin Historical Chart","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id_market_chart","description":"Coin Historical Chart","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko coin ID (e.g. bitcoin, solana)"},"vs_currency":{"type":"string","description":"Target currency (e.g. usd)"},"days":{"type":"string","description":"Number of days (e.g. 1, 7, 30, max)"}},"required":["id","vs_currency"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}/market_chart/range","pricePerCall":0.008,"description":"Coin Market Chart Range","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id_market_chart_","description":"Coin Market Chart Range","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko coin ID (e.g. bitcoin, solana)"},"vs_currency":{"type":"string","description":"Target currency (e.g. usd)"},"from":{"type":"string","description":"Unix timestamp start"},"to":{"type":"string","description":"Unix timestamp end"}},"required":["id","vs_currency","from","to"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}/ohlc","pricePerCall":0.008,"description":"Coin OHLC","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id_ohlc","description":"Coin OHLC","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko coin ID (e.g. bitcoin, solana)"},"vs_currency":{"type":"string","description":"Target currency (e.g. usd)"},"days":{"type":"string","description":"Number of days (e.g. 1, 7, 30)"}},"required":["id","vs_currency","days"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/{id}/tickers","pricePerCall":0.008,"description":"Coin Tickers","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_id_tickers","description":"Coin Tickers","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko coin ID (e.g. bitcoin, solana)"},"page":{"type":"integer","description":"Page number"},"depth":{"type":"integer","description":"Depth"},"order":{"type":"string","description":"Order"},"exchange_ids":{"type":"string","description":"Comma-separated exchange IDs"}},"required":["id"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/list","pricePerCall":0.008,"description":"Coins List (ID Map). WARNING: Do NOT set include_platform=true — it returns 10,000+ coins and overflows context. Use coins_markets instead for specific coins.","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_list","description":"Coins List (ID Map). WARNING: Do NOT set include_platform=true — returns 10,000+ coins. Use coins_markets for specific coins instead.","inputSchema":{"type":"object","properties":{"include_platform":{"type":"boolean","default":false,"description":"Include platform + contract addresses. WARNING: Setting true returns 10,000+ coins — do NOT use this."}},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/coins/markets","pricePerCall":0.008,"description":"Coins Markets — preferred way to get market data for specific coins. Pass comma-separated CoinGecko IDs.","method":"GET","tools":[{"name":"apis_v2_coingecko_coins_markets","description":"Coins Markets — preferred way to get market data for specific coins. Pass comma-separated CoinGecko IDs.","inputSchema":{"type":"object","properties":{"ids":{"type":"string","description":"Comma-separated CoinGecko coin IDs (e.g. bitcoin,solana,pump-fun)"},"page":{"type":"integer","default":1,"description":"Page number"},"order":{"type":"enum","default":"market_cap_desc","description":"Sort order"},"category":{"type":"string","description":"Filter by category"},"per_page":{"type":"integer","default":100,"maximum":250,"minimum":1,"description":"Results per page"},"sparkline":{"type":"boolean","default":false,"description":"Include sparkline"},"vs_currency":{"type":"string","description":"Target currency (e.g. usd)"},"price_change_percentage":{"type":"string","description":"Comma-separated windows: 1h,24h,7d,14d,30d,200d,1y"}},"required":["vs_currency"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/exchanges","pricePerCall":0.008,"description":"Exchanges List","method":"GET","tools":[{"name":"apis_v2_coingecko_exchanges","description":"Exchanges List","inputSchema":{"type":"object","properties":{"page":{"type":"integer","description":"Page number"},"per_page":{"type":"integer","description":"Results per page"}},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/exchanges/{id}","pricePerCall":0.008,"description":"Exchange Data by ID","method":"GET","tools":[{"name":"apis_v2_coingecko_exchanges_id","description":"Exchange Data by ID","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The exchange ID (e.g. binance, coinbase)"}},"required":["id"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/exchanges/{id}/tickers","pricePerCall":0.008,"description":"Exchange Tickers","method":"GET","tools":[{"name":"apis_v2_coingecko_exchanges_id_tickers","description":"Exchange Tickers","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The exchange ID (e.g. binance, coinbase)"},"page":{"type":"integer","description":"Page number"},"depth":{"type":"integer","description":"Depth"},"order":{"type":"string","description":"Order"},"coin_ids":{"type":"string","description":"Comma-separated coin IDs"}},"required":["id"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/exchanges/list","pricePerCall":0.008,"description":"Exchanges List (ID Map)","method":"GET","tools":[{"name":"apis_v2_coingecko_exchanges_list","description":"Exchanges List (ID Map)","inputSchema":{"type":"object","properties":{},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/news","pricePerCall":0.008,"description":"Crypto News","method":"GET","tools":[{"name":"apis_v2_coingecko_news","description":"Crypto News","inputSchema":{"type":"object","properties":{},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/search/trending","pricePerCall":0.008,"description":"Trending Search — returns top trending coins with their CoinGecko IDs. Use these IDs with coins_id to get platform/contract data.","method":"GET","tools":[{"name":"apis_v2_coingecko_search_trending","description":"Trending Search — returns top trending coins with their CoinGecko IDs. Use these IDs with coins_id to get platform/contract data.","inputSchema":{"type":"object","properties":{},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/simple/price","pricePerCall":0.008,"description":"Simple Price","method":"GET","tools":[{"name":"apis_v2_coingecko_simple_price","description":"Simple Price","inputSchema":{"type":"object","properties":{"ids":{"type":"string","description":"Comma-separated CoinGecko coin IDs (e.g. bitcoin,solana)"},"precision":{"type":"string","description":"Decimal precision"},"vs_currencies":{"type":"string","description":"Comma-separated target currencies (e.g. usd)"},"include_24hr_vol":{"type":"boolean","description":"Include 24h volume"},"include_market_cap":{"type":"boolean","description":"Include market cap"},"include_24hr_change":{"type":"boolean","description":"Include 24h change"},"include_last_updated_at":{"type":"boolean","description":"Include last updated timestamp"}},"required":["ids","vs_currencies"]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/simple/supported_vs_currencies","pricePerCall":0.008,"description":"Supported Currencies","method":"GET","tools":[{"name":"apis_v2_coingecko_simple_supported_vs_cu","description":"Supported Currencies","inputSchema":{"type":"object","properties":{},"required":[]}}]},
    {"name":"coingecko","endpoint":"https://api.aisa.one/apis/v2/coingecko/simple/token_price/{id}","pricePerCall":0.008,"description":"Coin Price by Token Address. The id parameter is the platform/chain ID (e.g. solana, ethereum).","method":"GET","tools":[{"name":"apis_v2_coingecko_simple_token_price_id","description":"Coin Price by Token Address. The id parameter is the platform/chain ID (e.g. solana, ethereum).","inputSchema":{"type":"object","properties":{"id":{"type":"string","description":"The CoinGecko platform/chain ID (e.g. solana, ethereum, base)"},"vs_currencies":{"type":"string","description":"Comma-separated target currencies (e.g. usd)"},"contract_addresses":{"type":"string","description":"Comma-separated contract addresses"},"include_24hr_vol":{"type":"boolean","description":"Include 24h volume"},"include_market_cap":{"type":"boolean","description":"Include market cap"},"include_24hr_change":{"type":"boolean","description":"Include 24h change"},"include_last_updated_at":{"type":"boolean","description":"Include last updated timestamp"}},"required":["id","contract_addresses","vs_currencies"]}}]}
  ],
  "appearance":{"skin":0,"hairStyle":10,"hair":6,"shirt":8,"pants":5,"accessory":1,"accent":0,"beard":0,"eyeColor":1,"headFeature":0}
}'::jsonb WHERE name = 'CoinGecko';
